### ISSUE TITLE
[Feature] 로그인 시 회원 아이디로 로그인하도록 변경

### ISSUE THREAD

**Issue by kyeong-hyeok** [DONGA-ST-A/Backend#20]
## 💡 이슈 내용
로그인 시 회원 아이디로 로그인하도록 변경

## To-do
- [x] 로그인 관련 코드 변경
- [x] 회원가입 로직 수정 -> 회원 아이디에 대한 validation 추가
- [x] JWT CLAIM을 회원 아이디로 변경
- [x] JWT 관련 클래스 수정
