### ISSUE TITLE
[Feature] FAQ 생성 기능 구현

### ISSUE THREAD

**Issue by kyeong-hyeok** [DONGA-ST-A/Backend#35]
## 💡 이슈 내용
FAQ 생성 기능 구현

## To-do
- [x] 관련 클래스 추가
- [x] FAQ 생성 기능 구현
- [x] ExceptionHandler -> MethodArgumentNotValidException 예외 처리 추가
- [x] Controller 테스트 코드 추가
