### ISSUE TITLE
[Feature] 상품 Entity 수정

### ISSUE THREAD

**Issue by kyeong-hyeok** [DONGA-ST-A/Backend#37]
## 💡 이슈 내용
상품 Entity 수정

## To-do
- [x] 상품 이미지 Entity 수정
- [x] 상품 Entity 필드 수정
- [x] SetTagConverter 추가 및 적용
