### ISSUE TITLE
[Feature] 상품 목록 조회 기능 구현

### ISSUE THREAD

**Issue by kyeong-hyeok** [DONGA-ST-A/Backend#47]
## 💡 이슈 내용
상품 목록 조회 기능 구현

## To-do
- [ ] SetTagConverter 수정
- [ ] Item 관련 Entity 수정 및 data.sql 추가
- [ ] 상품 목록 조회 기능 구현
- [ ] Controller 테스트 코드 추가
